import React from 'react';
import { MapTerrain } from '../../components/MapTerrain/MapTerrain';
import { TerrainType } from '../../utils/TerrainType';
import './Display.css'

{/*const initial = [
    {
        index: 0,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 1,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 2,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 3,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 4,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 5,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 6,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 7,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 8,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 9,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 10,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 11,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 12,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 13,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 14,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 15,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 16,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 17,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 18,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 19,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 20,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 21,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 0,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 1,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 2,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 3,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 4,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 5,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 6,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 7,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 8,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 9,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 10,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 11,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 12,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 13,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 14,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 15,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 16,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 17,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 18,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 19,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 20,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 21,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 0,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 1,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 2,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 3,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 4,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 5,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 6,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 7,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 8,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 9,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 10,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 11,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 12,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 13,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 14,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 15,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 16,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 17,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 18,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 19,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 20,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
    {
        index: 21,
        type: '',
        visibility: true,
        potion: false,
        sword: false,
        shield: false,
        boss: false,
        bossType: 0,
        player: false,
    },
]*/}

interface DisplayProps{
    rows: number,
    columns: number,
    terrains: TerrainType[],
}

export const Display: React.FC<DisplayProps> = ( {rows, columns, terrains} ) => {

    return(
        <div className='displayContainer' style={{gridTemplateColumns: `repeat(${columns}, 62px)`, gridTemplateRows: `repeat(${rows}, 62px)`}}>
           {terrains.map(({ index, type, visibility, potion, sword, shield, boss, bossType, player }) => {
               return <MapTerrain
               rows = {rows}
               columns = {columns}
               index = {index}
               type = {type}
               visibility = {visibility}
               potion = {potion}
               sword = {sword}
               shield = {shield}
               boss = {boss}
               bossType = {bossType}
               player = {player}
               ></MapTerrain>
           })}
        </div>
    );
}